import { AckStatus } from '../util/Constants'

module.exports = ({
  ack,
  body,
  broadcast,
  caption,
  chat,
  chatId,
  content,
  from,
  id,
  invis,
  isForwarded,
  isGroupMsg,
  isMMS,
  isMedia,
  isNewMsg,
  isNotification,
  isPSA,
  labels,
  lat,
  lng,
  loc,
  mediaData,
  mimetype,
  notifyName,
  quotedMsgObj,
  recvFresh,
  self,
  sender,
  star,
  t,
  timestamp,
  to,
  type,
}) => ({
  id,
  from,
  to,
  body,
  from_me: Boolean(sender.isMe),
  status: !Boolean(sender.isMe) ? AckStatus[2] : AckStatus[ack] || AckStatus.UNKNOWN,
  type,
  has_media: Boolean(isMedia),
  timestamp,
  from_group: Boolean(isGroupMsg),
  is_forwarded: Boolean(isForwarded),
  broadcast: Boolean(broadcast)
})
